---
title: Title here
subtitle: Do you have a subtitle? If so, write it here
titlerunning: Short form of title (if too long for head)
authorrunning: Short form of author list if too long for running head
thanks: | 
    Grants or other notes about the article that should go on the front 
    page should be placed here. General acknowledgments should be placed at the
    end of the article.

authors: 
- name: Äüthör 1
  address: Department of YYY, University of XXX
  email: abc@def
  
- name: Âuthóř 2
  address: Department of ZZZ, University of WWW
  email: djf@wef

keywords:
- key
- dictionary
- word

#PACS: 
#- PAC1
#- superPAC
    
MSC:
- MSC code 1
- MSC code 2

abstract: |
  The text of your abstract.  150 -- 250 words.

bibliography: bibliography.bib
biblio-style: spphys
# bibstyle options spbasic(default), spphys, spmpsci
output: rticles::springer_article
---

# Introduction {#intro}

- Modeling soils long term across years.
- Looking for the response to the active layer dynamics
- We should expect to see changes in the active layer (the depth) to increase as time since disturbance increases.
- We will need to assume some type of regeneration of the aboveground canopy and how that affects the inputs.
- Probably should propose different types of restoration over a century (determine some plausible responses)
- We have a model parameterized, so we can evaluate how each model does against current states and if the active layer can be parameterized.
- I think the growth in the active layer over time makes sense, assuming that some of the weather conditions remain constant (as I recall we took an ensemble average of things, so that should be ok.)

Your text comes here. Separate text sections with \cite{Mislevy06Cog}.

# Methods
- Canadian data, describe the model briefly (probably should follow on with it)
- Examine the processing of data
- 


# Results
- Map of the geographic locations of the different sites
- Map of the simulated weather conditions over time (along with averages + data)
- 3 panel graph on the active layer over time, comparison with data (over the course of the given year)
- Graph of growth of aboveground vegetation over time, compared to data
# Discussion

# Section title {#sec:1}

Text with citations by \cite{Galyardt14mmm}.

## Subsection title {#sec:2}

as required. Don't forget to give each section
and subsection a unique label (see Sect. \ref{sec:1}).

#### Paragraph headings 

Use paragraph headings as needed.

\begin{align}
a^2+b^2=c^2
\end{align}


